[[query]]
name="All entities and their types"
query="""SELECT ?ent ?type WHERE {
    ?ent rdf:type ?type .
    ?type rdfs:subClassOf* s223:Concept
}"""

[[query]]
name="All Systems"
description="Query all systems"
query="""SELECT ?sys WHERE {
    ?sys rdf:type/rdfs:subClassOf* s223:System .
}"""

[[query]]
name="Temperature Sensors"
description="find sensors that measure temperature"
query="""SELECT ?sensor ?location WHERE {
    ?sensor rdf:type/rdfs:subClassOf* s223:Sensor .
    ?sensor s223:observes ?property .
    ?property qudt:hasQuantityKind quantitykind:Temperature .
    ?sensor s223:hasObservationLocation ?location
}"""

[[query]]
name="What are all the temperature sensors?"
query="""SELECT ?sensor
WHERE {
?sensor a s223:TemperatureSensor .
?sensor s223:hasObservationLocation ?observe_location .
?sensor s223:hasPhysicalLocation ?physical_location .
}"""

[[query]]
name="Does the supply air contain recirculated air?"
query="""SELECT * WHERE {
?start a/rdfs:subClassOf* s223:Device .
?start s223:connectedTo ?ds .
?ds a s223:DomainSpace .
?ds s223:hasDomain s223:Domain-HVAC .
?start s223:connectedTo+ ?thing .
FILTER (?start = ?thing) .
}"""
